import { onMounted, onUnmounted, nextTick } from 'vue'
import { Fancybox } from '@fancyapps/ui'
import '@fancyapps/ui/dist/fancybox/fancybox.css'

// Hook responsible for initializing Fancybox after component mount and updates
export function useFancybox(
  selector: string = '[data-fancybox="markdown-gallery"]',
  options: Record<string, unknown> = {},
) {
  const initializeFancybox = (): void => {
    // Fancybox 5+ recommends using bind/unbind or destroy
    Fancybox.destroy()

    // Use nextTick to ensure MDX-rendered content is fully in the DOM
    nextTick(() => {
      if (document.querySelector(selector)) {
        Fancybox.bind(selector, {
          // Prevent Fancybox from modifying URL hash, which causes page jumps
          Hash: false,
          ...options,
        })
        console.log('Fancybox bound to selector:', selector)
      }
    })
  }

  // 1. Execute initialization after component mount
  onMounted(() => {
    // Execute binding on first mount
    initializeFancybox()
  })

  // 2. Listen for route changes or content updates (if content is dynamically loaded, e.g., route switching)
  // If your MDX content is updated via Vue component props, you need to additionally watch props changes and call initializeFancybox.
  // Here, we assume we only need to handle initial load and unmount, as the HTML structure generated by the rehype plugin is static.

  // 3. Destroy instance when component unmounts
  onUnmounted(() => {
    Fancybox.destroy()
    console.log('Fancybox instance destroyed')
  })

  // Return initialization function, allowing external manual re-binding (e.g., after dynamic content loads)
  return {
    reinitialize: initializeFancybox,
  }
}
